### Loops & Dictionaries

You are goin to create a nested dictionary of recipes, with keys at the top level and dictionaries as their associated values. 

1. First, create an empty dictionary.
2. Add three dishes as the top keys of your dictionary (e.g. 'meat pie')
3. For each key, add its paired value. The value should be another dictionary consisting of ingredient:amount pairs. (eg 'sugar': 'two cups') Each dish should have three ingredients.
4. Write a function to process the recipe dictionary. This function should loop through the recipes and return a *list* of ingredients for each recipe.

In [10]:
myDict = {}
myDict['lemon bars'] = {'lemons': '6', 'sugar': '3 cups'}
myDict['key lime pie'] = {'limes': '8', 'sugar': '2 cups'}
myDict['apple pie'] = {'apples': '7', 'sugar': '1 cup'}
myDict

{'lemon bars': {'lemons': '6', 'sugar': '3 cups'},
 'key lime pie': {'limes': '8', 'sugar': '2 cups'},
 'apple pie': {'apples': '7', 'sugar': '1 cup'}}

In [23]:
ingredients = []
for i in myDict:
    for j in myDict[i].keys():
        ingredients.append(j)
ingredients

['lemons', 'sugar', 'limes', 'sugar', 'apples', 'sugar']

### Coding readibility

1. Rewrite the code below in a 'best practice way'

In [1]:
def blabla():
    
    # A function that does blah
    
    for i in range(10):
        for j in range(10):
            for k in range(10): 
                print(i,j,k) 
                
    return everything

IndentationError: expected an indented block (<ipython-input-1-190831c477dd>, line 2)

In [ ]:
## Add comments here
# Add a description of what the function does.
# Four spaces for indentation
# Space things out for readability

### Data cleaning

1. read data from https://www.kaggle.com/jsphyg/weather-dataset-rattle-package 
2. Add a month column and a year column
3. print out the name of the columns where there are missing values 
4. Write a function if_no_rainToday_zero_rainfall to fill in the missing values in no rain today column according to zero rainfall column
5. fill in the other float columns with their median
6. Create a dummy variable from month column

In [113]:
import pandas as pd

In [129]:
df = pd.read_csv('weatherAUS.csv')
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [130]:
df['Year'] = df.Date.apply(lambda x: x[0:4])

In [131]:
df['Month'] = df.Date.apply(lambda x: x[5:7])

In [132]:
df['Month'] = df.Month.apply(lambda x: x.replace("-",""))

In [133]:
df[['Month', 'Year']].head()

  Month  Year
0    12  2008
1    12  2008
2    12  2008
3    12  2008
4    12  2008

In [134]:
df.columns[df.isnull().any()]

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday'],
      dtype='object')

In [137]:
# This isn't working out, so I moved on 
import numpy as np
def if_no_rainToday_zero_rainfall(x):
    if np.isnan(x):
       x = 0.0

In [138]:
df["Rainfall"] = df["Rainfall"].apply(if_no_rainToday_zero_rainfall)

In [139]:
df = df.fillna(df.median())

In [140]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow,Year,Month
0,2008-12-01,Albury,13.4,22.9,None,4.8,8.5,W,44.0,W,...,1007.1,8.0,5.0,16.9,21.8,No,0.0,No,2008,12
1,2008-12-02,Albury,7.4,25.1,None,4.8,8.5,WNW,44.0,NNW,...,1007.8,5.0,5.0,17.2,24.3,No,0.0,No,2008,12
2,2008-12-03,Albury,12.9,25.7,None,4.8,8.5,WSW,46.0,W,...,1008.7,5.0,2.0,21.0,23.2,No,0.0,No,2008,12
3,2008-12-04,Albury,9.2,28.0,None,4.8,8.5,NE,24.0,SE,...,1012.8,5.0,5.0,18.1,26.5,No,1.0,No,2008,12
4,2008-12-05,Albury,17.5,32.3,None,4.8,8.5,W,41.0,ENE,...,1006.0,7.0,8.0,17.8,29.7,No,0.2,No,2008,12

In [141]:
pd.get_dummies(df, columns=['Month'])

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Month_03,Month_04,Month_05,Month_06,Month_07,Month_08,Month_09,Month_10,Month_11,Month_12
0,2008-12-01,Albury,13.4,22.9,None,4.8,8.5,W,44.0,W,...,0,0,0,0,0,0,0,0,0,1
1,2008-12-02,Albury,7.4,25.1,None,4.8,8.5,WNW,44.0,NNW,...,0,0,0,0,0,0,0,0,0,1
2,2008-12-03,Albury,12.9,25.7,None,4.8,8.5,WSW,46.0,W,...,0,0,0,0,0,0,0,0,0,1
3,2008-12-04,Albury,9.2,28.0,None,4.8,8.5,NE,24.0,SE,...,0,0,0,0,0,0,0,0,0,1
4,2008-12-05,Albury,17.5,32.3,None,4.8,8.5,W,41.0,ENE,...,0,0,0,0,0,0,0,0,0,1
5,2008-12-06,Albury,14.6,29.7,None,4.8,8.5,WNW,56.0,W,...,0,0,0,0,0,0,0,0,0,1
6,2008-12-07,Albury,14.3,25.0,None,4.8,8.5,W,50.0,SW,...,0,0,0,0,0,0,0,0,0,1
7,2008-12-08,Albury,7.7,26.7,None,4.8,8.5,W,35.0,SSE,...,0,0,0,0,0,0,0,0,0,1
8,2008-12-09,Albury,9.7,31.9,None,4.8,8.5,NNW,80.0,SE,...,0,0,0,0,0,0,0,0,0,1
9,2008-12-10,Albury,13.1,30.1,None,4.8,8.5,W,28.0,S,...,0,0,0,0,0,0,0,0,0,1
10,2008-12-11,Albury,13.4,30.4,None,4.8,8.5,N,30.0,SSE,...,0,0,0,0,0,0,0,0,0,1
11,2008-12-12,Albury,15.9,21.7,None,4.8,8.5,NNE,31.0,NE,...,0,0,0,0,0,0,0,0,0,1
12,2008-12-13,Albury,15.9,18.6,None,4.8,8.5,W,61.0,NNW,...,0,0,0,0,0,0,0,0,0,1
13,2008-12-14,Albury,12.6,21.0,None,4.8,8.5,SW,44.0,W,...,0,0,0,0,0,0,0,0,0,1
14,2008-12-16,Albury,9.8,27.7,None,4.8,8.5,WNW,50.0,NaN,...,0,0,0,0,0,0,0,0,0,1
15,2008-12-17,Albury,14.1,20.9,None,4.8,8.5,ENE,22.0,SSW,...,0,0,0,0,0,0,0,0,0,1
16,2008-12-18,Albury,13.5,22.9,None,4.8,8.5,W,63.0,N,...,0,0,0,0,0,0,0,0,0,1
17,2008-12-19,Albury,11.2,22.5,None,4.8,8.5,SSE,43.0,WSW,...,0,0,0,0,0,0,0,0,0,1
18,2008-12-20,Albury,9.8,25.6,None,4.8,8.5,SSE,26.0,SE,...,0,0,0,0,0,0,0,0,0,1
19,2008-12-21,Albury,11.5,29.3,None,4.8,8.5,S,24.0,SE,...,0,0,0,0,0,0,0,0,0,1
20,2008-12-22,Albury,17.1,33.0,None,4.8,8.5,NE,43.0,NE,...,0,0,0,0,0,0,0,0,0,1
21,2008-12-23,Albury,20.5,31.8,None,4.8,8.5,WNW,41.0,W,...,0,0,0,0,0,0,0,0,0,1
22,2008-12-24,Albury,15.3,30.9,None,4.8,8.5,N,33.0,ESE,...,0,0,0,0,0,0,0,0,0,1
23,2008-12-25,Albury,12.6,32.4,None,4.8,8.5,W,43.0,E,...,0,0,0,0,0,0,0,0,0,1
24,2008-12-26,Albury,16.2,33.9,None,4.8,8.5,WSW,35.0,SE,...,0,0,0,0,0,0,0,0,0,1
25,2008-12-27,Albury,16.9,33.0,None,4.8,8.5,WSW,57.0,NaN,...,0,0,0,0,0,0,0,0,0,1
26,2008-12-28,Albury,20.1,32.7,None,4.8,8.5,WNW,48.0,N,...,0,0,0,0,0,0,0,0,0,1
27,2008-12-29,Albury,19.7,27.2,None,4.8,8.5,WNW,46.0,NW,...,0,0,0,0,0,0,0,0,0,1
28,2008-12-30,Albury,12.5,24.2,None,4.8,8.5,WNW,50.0,WSW,...,0,0,0,0,0,0,0,0,0,1
29,2008-12-31,Albury,12.0,24.4,None,4.8,8.5,W,39.0,WNW,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142163,2017-05-26,Uluru,14.3,27.6,None,4.8,8.5,WNW,39.0,NaN,...,0,0,1,0,0,0,0,0,0,0
142164,2017-05-27,Uluru,9.3,28.0,None,4.8,8.5,W,28.0,SSW,...,0,0,1,0,0,0,0,0,0,0
142165,2017-05-28,Uluru,8.0,24.6,None,4.8,8.5,E,33.0,SE,...,0,0,1,0,0,0,0,0,0,0
142166,2017-05-29,Uluru,12.7,22.2,None,4.8,8.5,E,37.0,E,...,0,0,1,0,0,0,0,0,0,0
142167,2017-05-30,Uluru,9.4,22.7,None,4.8,8.5,E,35.0,SE,...,0,0,1,0,0,0,0,0,0,0
142168,2017-05-31,Uluru,5.4,20.5,None,4.8,8.5,E,46.0,E,...,0,0,1,0,0,0,0,0,0,0
142169,2017-06-01,Uluru,5.6,19.4,None,4.8,8.5,E,43.0,E,...,0,0,0,1,0,0,0,0,0,0
142170,2017-06-02,Uluru,1.5,19.2,None,4.8,8.5,E,37.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142171,2017-06-03,Uluru,3.8,19.8,None,4.8,8.5,ENE,39.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142172,2017-06-04,Uluru,4.5,18.8,None,4.8,8.5,E,31.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142173,2017-06-05,Uluru,4.9,20.7,None,4.8,8.5,E,37.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142174,2017-06-06,Uluru,1.2,20.8,None,4.8,8.5,E,43.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142175,2017-06-07,Uluru,0.5,21.7,None,4.8,8.5,E,43.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142176,2017-06-08,Uluru,4.0,20.0,None,4.8,8.5,SE,39.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142177,2017-06-09,Uluru,3.4,19.8,None,4.8,8.5,E,43.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142178,2017-06-10,Uluru,3.2,18.6,None,4.8,8.5,E,46.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142179,2017-06-11,Uluru,2.4,19.1,None,4.8,8.5,E,33.0,SE,...,0,0,0,1,0,0,0,0,0,0
142180,2017-06-12,Uluru,5.1,19.7,None,4.8,8.5,E,46.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142181,2017-06-13,Uluru,2.5,21.2,None,4.8,8.5,ENE,35.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142182,2017-06-14,Uluru,2.3,21.4,None,4.8,8.5,SE,22.0,SE,...,0,0,0,1,0,0,0,0,0,0
142183,2017-06-15,Uluru,2.6,22.5,None,4.8,8.5,S,19.0,S,...,0,0,0,1,0,0,0,0,0,0
142184,2017-06-16,Uluru,5.2,24.3,None,4.8,8.5,E,24.0,SE,...,0,0,0,1,0,0,0,0,0,0
142185,2017-06-17,Uluru,6.4,23.4,None,4.8,8.5,ESE,31.0,S,...,0,0,0,1,0,0,0,0,0,0
142186,2017-06-18,Uluru,8.0,20.7,None,4.8,8.5,ESE,41.0,SE,...,0,0,0,1,0,0,0,0,0,0
142187,2017-06-19,Uluru,7.4,20.6,None,4.8,8.5,E,35.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142188,2017-06-20,Uluru,3.5,21.8,None,4.8,8.5,E,31.0,ESE,...,0,0,0,1,0,0,0,0,0,0
142189,2017-06-21,Uluru,2.8,23.4,None,4.8,8.5,E,31.0,SE,...,0,0,0,1,0,0,0,0,0,0
142190,2017-06-22,Uluru,3.6,25.3,None,4.8,8.5,NNW,22.0,SE,...,0,0,0,1,0,0,0,0,0,0
142191,2017-06-23,Uluru,5.4,26.9,None,4.8,8.5,N,37.0,SE,...,0,0,0,1,0,0,0,0,0,0
142192,2017-06-24,Uluru,7.8,27.0,None,4.8,8.5,SE,28.0,SSE,...,0,0,0,1,0,0,0,0,0,0

### Linear regression

1. What are the assumptions of linear regression?

Linearity
Normality (of the residuals)
Heteroscedacity

2. Explain the reasoning for each assumption

If the data isn't linear, you might need a different model. If the distribution of the residuals is skewed, then a linear model might be a good predictor for some values but not others (the ones that aren't evenly distributed).

3. Explain the concept of correlation. What is the covariance? Why don't we use covariance?

Two variables covary if a change in one correlates with a change in the other.

4. Should we use the correlation to decide on variables to delete from our model?

Multiple regression assumes that we can show how much a change in one feature affects the target holding the other features constant. If features affect each other, then we can't make that assumption.

5. What is R squared? How can it help us in comparing among models? 
What is the R squared of the baseline model?

R2 tells us how much variance in the target is explained by a change in x. It compares the errors of the regression line to the baseline (a line that always predicts the mean of y for any x).

6. Explain cross-validation. Why do we use it?   
[stretch] Create a function that does cross validation? (use sklearn, numpy etc.)

Cross validation helps us prevent misleading results due to performing only a single train/test split. If you only do one split, you might get a random sample that isn't representative (E.g. it has all of the lowest values in the distribution and none of the highest). If you train your data on that and only that, you won't get an accurate model.

7. How can we evaluate our model besides R squared? and why would we want to? (hint: loss function)

Mean absolute error or mean squared error measure error while preventing positive and negative errors from cancelling each other out.

8. Using the X, Y variables created in the plotting section use the various packages 
to run a linear regression model

In [151]:
df_regression = df[['MinTemp', 'MaxTemp', 'Evaporation','Sunshine', 'WindGustSpeed','Temp9am', 'Temp3pm']]
X = df_regression
y = df['Rainfall']

In [152]:
import statsmodels.api as sm
predictors_int = sm.add_constant(X)
model = sm.OLS(y,predictors_int).fit()
model.summary()

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).

In [142]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow', 'Year', 'Month'],
      dtype='object')

9. Write down the equation of the resulting model

### Plotting

1. Use numpy random normal to create 100 points for an X variable 
2. Use numpy random normal to create 100 points for a Y Variable
2. Plot it as a scatter plot and as a histogram 
3. Place the plots side by side 
4. change the figure size to 12x15

# Done